Algoritmo "semnome"
//  
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 15/07/2020
Var
// Seção de Declarações das variáveis 
 grau1, celcius: real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Digite a temperatura em Fahrenheit")
leia(grau1)

celcius <- (grau1 - 32)/1.8

escreval("A temperatura em graus Celcius é de : ", celcius)

Fimalgoritmo